version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8080:8080" 
    environment:
      SPARK_HOME: /opt/spark
      ZEPPELIN_LOCAL_IP: 0.0.0.0
      ZEPPELIN_LOG_DIR: ./logs
      ZEPPELIN_NOTEBOOK_DIR: ./notebook
    volumes:
      - ./spark-2.2.0-bin-hadoop2.7:/opt/spark
      - ./jars/hive-jdbc-2.3.2-standalone.jar:/opt/zeppelin/interpreter/jdbc/hive-jdbc-2.3.2-standalone.jar
      - ./jars/hadoop-common-2.6.0.jar:/opt/zeppelin/interpreter/jdbc/hadoop-common-2.6.0.jar
      - ./co2.csv:/data
      - ./notebook:/notebook
      - ./logs:/logs

    restart: always

volumes:
  namenode:
  datanode:
  # spark:
